public class ContohVariabel12 {
    public static void main(String[] args) {
            String HobiSayaAdalah = "Bermain Petak Umpet";
            boolean Pandai = true;
            char JenisKelamin = 'L';
            byte UmurSayaSekarang = 18;
            double IPK = 3.78, tinggi = 160;
            System.out.println(HobiSayaAdalah);
            System.out.println("Apakah pandai?" + Pandai);
            System.out.println("Jenis kelamin:" + JenisKelamin);
            System.out.println("Umurku saat ini:" + UmurSayaSekarang);
            System.out.println(String.format("Saya beripk %s, dengan tinggi badan %s,", IPK, tinggi));
        }
        
    }
